asset/urls.py
from django.urls import path
from . import views

app_name    = "asset"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("asset.urls")),
    path('accounts/', include('allauth.urls')),
]

asset/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        db_table = "category"

    name = models.CharField(verbose_name="カテゴリ名",max_length=100)
    dt =models.DateTimeField(verbose_name="追加日", default=timezone.now)

    def __str__(self):
        return self.name

class Balance(models.Model):

    class Meta:
        db_table = "balance"

    category = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE,blank=True, null=True)


    title = models.CharField(verbose_name="タイトル", max_length=100, default="")
    comment = models.CharField(verbose_name="コメント", blank=True, max_length=2000)
    income = models.IntegerField(verbose_name="収入", default=0)
    spending = models.IntegerField(verbose_name="支出", default=0)
    dt = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    pay_dt  =  models.DateTimeField(verbose_name="決済日")

    def __str__(self):
        return self.comment

asset/forms.py
from django import forms
from .models import Balance

class BalanceForm(forms.ModelForm):
    class Meta:
        model     = Balance
        fields   = [ "category","title","comment","income","spending","pay_dt"]

#年の絞り込み(モデルを継承しないフォーム)
class YearForm(forms.Form):
    year    = forms.IntegerField()




asset/views.py
from django.shortcuts import render,redirect
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Balance,Category
from .forms import BalanceForm,YearForm

from django.db.models import Q


import datetime

class BalanceView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        categories  = Category.objects.all()

        #検索処理(TODO:この検索処理はオミットべきか？)
        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("asset:index")

            search      = request.GET["search"].replace(" ","　")
            search_list =search.split(" ")

            query       = Q()
            for word in search_list:

                query &= Q(title__contains=word)

            balances  = Balance.objects.filter(query)
        else:
            balances  = Balance.objects.all()



        #最古から最新の年リストを生成(決済日)
        dt          = datetime.datetime.now()
        now_year    = dt.year #←最新の決算日の年を当てるべきでは？
        years       = []

        balance     = Balance.objects.order_by("pay_dt").first()

        #最古のデータがあれば最古のデータの年から今年までのリストを作る。(これがテンプレートのselectタグになる。)
        #なければ今年だけ表示
        if balance:
            old_year    = balance.pay_dt.year
            print(old_year)
            for i in range(now_year,old_year-1,-1):
                years.append(i)
        else:
            years.append(now_year)



        #yearの指定があれば、年のデータを抜き取り検索する。指定がなければ現在の年を指定
        form            = YearForm(request.GET)
        selected_year   = now_year 
        
        if form.is_valid():
            data            = form.cleaned_data
            selected_year   = data["year"]

        #1年分のデータ
        balances    = Balance.objects.filter(pay_dt__year=selected_year).order_by("pay_dt")

        #月ごとのデータ
        months       = []
        for i in range(1,13):
            months.append( Balance.objects.filter(pay_dt__year=selected_year,pay_dt__month=i).order_by("pay_dt") )




        #小計値の計算(1年分)
        balances    = list(balances.values())
        total       = 0

        for balance in balances:

            total          = total + int(balance["income"]) - int(balance["spending"])
            balance["total"] = total

            #カテゴリ名を設定
            if balance["category_id"]:
                category            = Category.objects.filter(id=balance["category_id"]).first()
                balance["category"]   =category.name



        #小計値の計算(月ごと)←TODO:処理系が1年分と同じなので、関数化させるべきかと
        month_list  = []
        for month in months:

            month   = list(month.values())
            total   = 0

            #一ヶ月の中にある1レコード分ずつ処理
            for m in month:

                total       = total + int(m["income"]) - int(m["spending"])
                m["total"]  = total

                #カテゴリ名を設定
                if m["category_id"]:
                    category        = Category.objects.filter(id=m["category_id"]).first()
                    m["category"]   = category.name

            month_list.append(month)




        



        context = {"balances":balances,
                   "categories":categories,
                   "years":years,
                   "months":month_list,
                   "selected_year":selected_year,
                   }

        return render(request,"asset/index.html",context)

    def post(self, request, *args, **kwargs):

        form = BalanceForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("asset:index")

index   = BalanceView.as_view()

class BalanceDeleteView(LoginRequiredMixin,View):

    def post(self,request, pk, *args, **kwargs):

        balance = Balance.objects.filter(id=pk).first()
        balance.delete()

        return redirect("asset:index")

delete = BalanceDeleteView.as_view()

templates/asset/index.html
{% load static %}

<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <!-- cssは一部が不具合を起こしているようなので、全て書き換え-->
    <link rel="stylesheet" href="{% static 'asset/css/style.css' %}">
    <script src="{% static 'asset/js/script.js' %}"></script>

    <!--fontawesomeは
        https://fontawesome.com/download#pro-packages
        からFreeforWeb(CSSやJSが含まれている方)をDLして
        css(fontawesomeに改名)とwebfontをcommon/css/に配置
    -->

    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.min.css' %}">

    <style>
        body{
            background-image: url("{% static 'asset/img/ookamikun1.png' %}");
            background-attachment: fixed;
            background-size: cover;
            background-position: right 10% bottom 10%;
            }
    </style>
</head>
<body>

    <header>
        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">
        <div class="left_header">
        <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% url 'asset:index' %}"><h1>メニュー</h1></a>
            <div class="header_right_content">
                <!--TODO:ここにログインのアイコンなどを-->
            </div>
        </div>
        <div class="l_sidebar_menu">

            <a href="{% url 'account_logout' %}">ログアウト</a>

        </div>
        <label class="l_sidebar_closer" for="l_sidebar"></label>
    </header>

<main>
    <h1 style="text-align: right">オオカミ君の会計簿</h1>
    <form action="" method="get">
        <input type="text" name="search" placeholder="検索したいワード" value="{{ request.GET.search }}">
        <input type="submit" class="btn btn-outline-dark" value="検索">
    </form>
    <form action="" method="post">
    {% csrf_token %}

        <select name="category">
            <option value="">カテゴリを選んでください</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="title" placeholder="鑑定科目を入力してください" required>
        <input type="text" name="comment" placeholder="主な用途を入力してください">
        <input type="number" name="income" value="0">
        <input type="number" name="spending" value="0">
        <input id="pay_dt" type="text" name="pay_dt" readonly>
        <input class="btn btn-success" type="submit" value="投稿">
    </form>

    <form action="" method="GET">
        <select name="year">
            {% for year in years %}
            <option value="{{ year }}" {% if selected_year == year %}selected{% endif %}>{{ year }}年</option>
            {% endfor %}
        </select>
        <input type="submit" value="絞り込み">
    </form>
    

    <input id="tab_radio_0" class="tab_radio" type="radio" name="tab_system" checked><label class="tab_label" for="tab_radio_0">1年表示</label>
    <input id="tab_radio_1" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_1">1月</label>
    <input id="tab_radio_2" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_2">2月</label>
    <input id="tab_radio_3" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_3">3月</label>
    <input id="tab_radio_4" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_4">4月</label>
    <input id="tab_radio_5" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_5">5月</label>
    <input id="tab_radio_6" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_6">6月</label>
    <input id="tab_radio_7" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_7">7月</label>
    <input id="tab_radio_8" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_8">8月</label>
    <input id="tab_radio_9" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_9">9月</label>
    <input id="tab_radio_10" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_10">10月</label>
    <input id="tab_radio_11" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_11">11月</label>
    <input id="tab_radio_12" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_12">12月</label>

    <div id="tab_area_0" class="tab_area">{% include "asset/table.html" %}</div>
    {% for month in months %}
    <div id="tab_area_{{ forloop.counter }}" class="tab_area">{% include "asset/table.html" with balances=month %}</div>
    {% endfor %}

    </main>
</body>
</html>

templates/asset/table.html
{% load humanize %}

<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <!--idと登録日の表示は無くても良いかも知れない。紛らわしいかも-->
            <!--勘定科目とカテゴリは統一させるべき？勘定科目を1対多のカテゴリ式にする-->
            <td class="text-center">id</td>
            <td class="text-center">カテゴリ</td>
            <td class="text-center">鑑定項目</td>
            <td class="text-center">主な用途</td>
            <td class="text-center">収入金額</td>
            <td class="text-center">支出金額</td>
            <td class="text-center">小計</td>
            <td class="text-center">登録日</td>
            <td class="text-center">決算日</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
    {% for balance in balances %}
    <tr>
        <td>{{ balance.id }}</td>
        <td>{{ balance.category|default:"未分類" }}</td>
        <td>{{ balance.title }}</td>
        <td>{{ balance.comment }}</td>
        <td>{{ balance.income|default:"0"|intcomma }}</td>
        <td>{{ balance.spending|default:"0"|intcomma }}</td>
        <td>{{ balance.total|default:"0"|intcomma }}</td>
        <td>{{ balance.dt }}</td>
        <td>{{ balance.pay_dt|date:"Y年m月d日" }}</td>
        <td>
           <form action="{% url 'asset:delete' balance.id %}" method="POST">
               {% csrf_token %}
               <input class="btn btn-outline-dark" type="submit" value="削除">
           </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>